//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FizzBuzzWcf.WsdlFizzBuzz {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsdlFizzBuzz.IFizzBuzzService")]
    public interface IFizzBuzzService {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IFizzBuzzService/GetSerieFizzBuzz", ReplyAction = "http://tempuri.org/IFizzBuzzService/GetSerieFizzBuzzResponse")]
        string[] GetSerieFizzBuzz(int randomNumber);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFizzBuzzService/GetSerieFizzBuzz", ReplyAction="http://tempuri.org/IFizzBuzzService/GetSerieFizzBuzzResponse")]
        System.Threading.Tasks.Task<string[]> GetSerieFizzBuzzAsync(int randomNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFizzBuzzServiceChannel : FizzBuzzWcf.WsdlFizzBuzz.IFizzBuzzService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FizzBuzzServiceClient : System.ServiceModel.ClientBase<FizzBuzzWcf.WsdlFizzBuzz.IFizzBuzzService>, FizzBuzzWcf.WsdlFizzBuzz.IFizzBuzzService {
        
        public FizzBuzzServiceClient() {
        }
        
        public FizzBuzzServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FizzBuzzServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FizzBuzzServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FizzBuzzServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public string[] GetSerieFizzBuzz(int randomNumber)
        {
            return base.Channel.GetSerieFizzBuzz(randomNumber);
        }

        public System.Threading.Tasks.Task<string[]> GetSerieFizzBuzzAsync(int randomNumber) {
            return base.Channel.GetSerieFizzBuzzAsync(randomNumber);
        }
    }
}
